WebApplicationWithImageAndIcon/Controllers/PlayersController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplicationWithImageAndIcon.Models;
using WebApplicationWithImageAndIcon.Models.ViewModels;
using PagedList;
using System.Web.Services.Description;
using System.Data.Entity;

namespace WebApplicationWithImageAndIcon.Controllers
{    
    public class PlayersController : Controller
    {
        private readonly SportsDbContext db = new SportsDbContext();
        public ActionResult Index(string searchString, int page = 1)
        {
            IQueryable<Player> players = db.Players.Include("Sports");

            if (!string.IsNullOrEmpty(searchString))
            {
                players = players.Where(p => p.PlayerName.Contains(searchString));
            }
            return View(players.OrderBy(x => x.PlayerId).ToPagedList(page, 5));
        }
        public PartialViewResult Search(string searchString, Grade? searchGrade)
        {
            IQueryable<Player> players = db.Players.Include("Sports");

            if (!string.IsNullOrEmpty(searchString))
            {
                players = players.Where(p => p.PlayerName.Contains(searchString));
            }

            if (searchGrade != null)
            {
                players = players.Where(p => p.PlayerGrade == searchGrade);
            }

            return PartialView("_SearchResult", players.ToList());
        }


        public ActionResult Create()
        {
            ViewBag.sports = new SelectList(db.Sports, "SportsId", "SportsName");
            return View();
        }
        [HttpPost]
        public ActionResult Create(PlayerViewModel pvm)
        {
            if(ModelState.IsValid)
            {
                if(pvm.Picture != null)
                {
                    // Image save
                    string filePath = Path.Combine("~/Images", Guid.NewGuid().ToString() + Path.GetExtension(pvm.Picture.FileName));
                    pvm.Picture.SaveAs(Server.MapPath(filePath));

                    // for player
                    Player player = new Player
                    {
                        PlayerName = pvm.PlayerName,
                        JoinDate = pvm.JoinDate,
                        PlayerGrade = pvm.PlayerGrade,
                        SportsId = pvm.SportsId,
                        PicturePath = filePath
                    };
                    db.Players.Add(player);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            ViewBag.sports = new SelectList(db.Sports, "SportsId", "SportsName");
            return View(pvm);
        }
        public ActionResult Edit(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            Player player = db.Players.Find(id);
            if(player == null)
            {
                return HttpNotFound();
            }
            PlayerViewModel pvm = new PlayerViewModel
            {
                PlayerId = player.PlayerId,
                PlayerName = player.PlayerName,
                JoinDate = player.JoinDate,
                PlayerGrade = player.PlayerGrade,
                SportsId = player.SportsId,
                PicturePath = player.PicturePath
            };
            ViewBag.sports = new SelectList(db.Sports, "SportsId", "SportsName");
            return View(pvm);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(PlayerViewModel pvm)
        {
            if (ModelState.IsValid)
            {
                Player player = db.Players.Find(pvm.PlayerId);

                if (player == null)
                {
                    return HttpNotFound();
                }

                if (pvm.Picture != null && pvm.Picture.ContentLength > 0)
                {
                    // Image file exists, save and update the path
                    string filePath = Path.Combine("~/Images", Guid.NewGuid().ToString() + Path.GetExtension(pvm.Picture.FileName));
                    pvm.Picture.SaveAs(Server.MapPath(filePath));

                    player.PicturePath = filePath;
                }

                player.PlayerName = pvm.PlayerName;
                player.JoinDate = pvm.JoinDate;
                player.PlayerGrade = pvm.PlayerGrade;
                player.SportsId = pvm.SportsId;

                db.Entry(player).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            ViewBag.sports = new SelectList(db.Sports, "SportsId", "SportsName", pvm.SportsId);
            return View(pvm);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            Player player = db.Players.Find(id);
            if (player == null)
            {
                return HttpNotFound();
            }

            return View(player);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirm(int id)
        {
            Player player = db.Players.Find(id);
            db.Players.Remove(player);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

WebApplicationWithImageAndIcon/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Sports Management System</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar bg-primary bg-body-tertiary">
        <div class="container">
            @Html.ActionLink("World Sport", "Index", "Home", new { area = "" }, new { @class = "navbar-brand text-white"})
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                  <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link text-white" })</li>
                    <li>@Html.ActionLink("Sports", "Index", "Sports", new { area = "" }, new { @class = "nav-link text-white" })</li>
                    <li>@Html.ActionLink("Player", "Index", "Players", new { area = "" }, new { @class = "nav-link text-white" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <footer>
            <p class="text-center">&copy; @DateTime.Now.Year - www.sports.com</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/bootstrap.js"></script>
    @RenderSection("scripts", required: false)
    @RenderSection("styles", required: false)
</body>
</html>